export { default as Admin } from "./Admin"
export { default as Airplanes } from "./Airplanes"
export { default as Auth } from "./Auth"
export { default as Landing } from "./Landing"
export { default as Login } from "./Login"
export { default as Logout } from "./Logout"
export { default as Register } from "./Register"
